version: '3.9'

services:
 backend:
  build: ./backend
  container_name: backend_container
  ports:
   - '4000:4000'
  volumes:
   - ./backend:/app
  env_file:
   - ./backend/.env

 frontend:
  build: ./proyecto
  container_name: frontend_container
  ports:
   - '3000:3000'
  volumes:
   - ./proyecto:/app
  depends_on:
   - backend
  env_file:
   - ./proyecto/.env
  stdin_open: true
